twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
        default_path: '%kernel.project_dir%/templates'
        form_themes:
            - bootstrap_5_layout.html.twig
